### ISSUE TITLE
Posting API doesn't respect paragraphs in description

### ISSUE THREAD

**Issue by nettofarah** [lever/postings-api#11]
Hi!
I'm trying to integrate the posting API to our website, but for some reason the `posting` endpoint doesn't respect paragraphs in the `description` field.

Here's an example: 
https://jobs.lever.co/ifttt/b5b66238-b49f-461d-857b-ce04099d38c8
^ There's a title, 3 paragraphs and then 2 lists with bullet points.

Here's what I get back from the API: 
https://api.lever.co/v0/postings/ifttt/b5b66238-b49f-461d-857b-ce04099d38c8

```json
{
id: "b5b66238-b49f-461d-857b-ce04099d38c8",
text: "Infrastructure Engineer",
description: "You believe that speed is a feature and that anything can be automated. You are passionate about the design and deployment of large scale systems and take pride in the reliability of your services. You enjoy the detective work of solving mysteries through the strategic use of metrics and logging. You’ll join a tiny team tackling huge challenges in system design, automation, and developer happiness. As one of the first members of the infrastructure team, you’ll have the opportunity to shape the future of infrastructure at a company that’s processing over one billion API events per day and growing. IFTTT is fundamentally changing the way people interact with technology by helping them get the most out of their favorite products and services.",
...
}
```

Is there anything I can do to either get html (just like `lists`) or to get the description in different paragraphs?

**Comment by distracteddev** [comment]
@nettofarah Looking at the API response, I can see that the description has the appropriate `\n\n` characters to denote the 3 paragraphs.

**Comment by nettofarah** [comment]
Thank you @distracteddev. I think this makes sense.
My JSON viewer plugin must have swallowed the `\n`s.

**Comment by distracteddev** [comment]
Glad you're seeing the same thing! Thanks for writing in :)
