### ISSUE TITLE
Missing deltaContent field in README

### ISSUE THREAD

**Issue by richardxia** [lever/postings-api#13]
It looks like somewhat recently the JSON GET API now returns postings with an extra `deltaContent` field in the `lists` field, so rather than just returning `{text:NAME, content:"unstyled HTML of list elements"}`, it actually returns something like `{text:NAME, content:"unstyled HTML of list elements", deltaContent:{ops:[list of "operations"]}}`.

Can the README be updated to include this? We had some scripts break because they weren't expecting this new field.

**Comment by jonsadka** [comment]
@richardxia Thanks for letting us know. The issue should have been resolved and you should no longer be receiving `deltaContent`. Apologies for any confusion this may have caused.
