### ISSUE TITLE
Introduction of "descriptionPlain" breaks old clients

### ISSUE THREAD

**Issue by stadeltobi** [lever/postings-api#16]
The recent introduction of the additional response field "descriptionPlain" (see 15ded81c and especially d4d2d9625), along with the old field now suddenly containing markup unnecessarily breaks old clients that relied on the "description" field being plain text.

I'd suggest to do it the other way around, and do a "descriptionHtml" field or something, so that clients that want the new behaviour can get it, but old ones don't break.

**Comment by ispivak** [comment]
@stadeltobi thank you for the report. This change is related to us introducing Rich text formatting support in Lever job postings. When implementing this change, we have considered both options - the one you are recommending, and the way its currently implemented. Based on our testing and research, as well as  the desire for the description to reflect correctly the Rich text formatting we went with the current option. Please let us know if we can assist you in any way to fix your client - please contact support@lever.co with particular details and I can respond there as well.
