### ISSUE TITLE
`createdAt` field not documented and no correct (v0)

### ISSUE THREAD

**Issue by bcarradini** [lever/postings-api#35]
The response to `GET /v0/postings/SITE` includes an undocumented field for each job posting: `createdAt`. Based on the format of the data (e.g. `"createdAt": "1381340626859"`) I would expect the field to be an epoch timestamp, but none of the values returned by `GET https://api.lever.co/v0/postings/leverdemo?mode=json` can be parsed into sane date/time stamps. The documentation needs to be clarified re: this field and how it should be interpreted.

**Comment by DanDiplo** [comment]
@bcarradini Just a guess, but it _may_ be that the timestamp includes microseconds - in which case it would convert to Wednesday, October 9, 2013.  Maybe the demo job is old?  See https://www.epochconverter.com/

If true and your parser can't work that out, you can drop the last 3 digits to get `1381340626`  which is a more conventional timestamp. 

But would be good to get an official response...

**Comment by bcarradini** [comment]
@DanDiplo --- It _is_ in microseconds. <sigh>. Sorry about that! All good.
