### ISSUE TITLE
Is there any plan to expose custom questions through the Postings API?

### ISSUE THREAD

**Issue by mrhwick** [lever/postings-api#4]
My team's postings are reliant on custom questions to gather the necessary information from applicants. Is there any plan to expose custom questions in the future?

**Comment by jackerman** [comment]
Hi @mrhwick! Thanks for reaching out. We do have custom question support through our API on our roadmap. However, it won't come in the next few weeks. I will be sure to let you know when it is supported. Feel free to send up a note at support@lever.co if any additional questions come to mind. We're always happy to help!

**Comment by trevanhetzel** [comment]
I know this is closed, but any idea when this will be coming? Getting postings from the API is pretty pointless for us without this :(

**Comment by jackerman** [comment]
Hey @trevanhetzel! Totally hear ya. I don't have a specific estimate at the moment, but we totally hear the user need here. I'll be sure to circle back with you as soon as I have a specific estimate to share. Thanks for your patience!
