### ISSUE TITLE
Multiple values for location, commitment, and team query parameters are not respected

### ISSUE THREAD

**Issue by seanabrahams** [lever/postings-api#5]
For the query parameters that support multiple values (location, commitment, team) the documentation (https://github.com/lever/postings-api#get-a-list-of-job-postings) states: "You can specify multiple values and they are OR'ed together"

However when specifying multiple values it appears only the first value is used.

Example: https://api.lever.co/v0/postings/leverdemo?location=Mountain%20View&location=San%20Francisco&mode=json only returns jobs for Mountain View and not San Francisco.

If passing in multiple `location` parameters isn't the correct format, it would be good to update the documentation with an example. I tried comma separated as well without luck. Thanks!

**Comment by bruchu** [comment]
this is working for me.
