### ISSUE TITLE
POST endpoints?

### ISSUE THREAD

**Issue by TrevorAustin** [lever/postings-api#9]
Hi Lever!

My team is migrating to hosting all our job descriptions and interview questions in version control so we can better collaborate and track changes over time. We'd love to be able to script pushing the latest versions up to Lever - are POST versions of these endpoints anywhere on the road map?

**Comment by bruchu** [comment]
Hi Trevor, 

This is on our roadmap but not yet available for our authenticated API, aptly named "Lever API". The Lever API documentation is available from the Settings > Integrations > API section of the Lever App.

-b

**Comment by ankitmca08** [comment]
Resume is upload is not working when we try using gravity form.

**Comment by To1ne** [comment]
Any news on this? This issue is more than a year old, but I don't see any movement.

@bruchu Is this still on the roadmap?

**Comment by rkstedman** [comment]
Hello! Unfortunately, being able to create or update job postings and interview questions via the API isn't something on the foreseeable roadmap.
